apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: consumer-iaa-01-deployer
spec:
  project: default
  source:
    repoURL: https://code.europa.eu/api/v4/projects/1402/packages/helm/stable
    chart: consumer-iaa
    targetRevision: 0.0.1-F-feature-initial-commit.6.bcc1fd65
    helm:
      values: |
        values:
          branch: feature/initial-commit

        project: default

        namespaceTag:
          consumer: consumer01
          common: common01

        domainSuffix: sandbox-iaa.simpl-europe.eu

        resourcePreset: default

        argocd:
          appname: consumer01
          namespace: argocd

        cluster:
          address: https://kubernetes.default.svc
          namespace: consumer01
          commonToolsNamespace: common01
          issuer: dev-prod-http

        secrets:
          role: sandbox-iaa-role
          secretEngine: sandbox-iaa
  destination:
    server: https://kubernetes.default.svc
    namespace: authority01
